"use client";
import{useEffect,useMemo,useState}from"react";
import{STATUS_LABELS,getProjectProgress,loadProjects,ProjectRecord}from"../lib/storage";
const yen=(n:number)=>new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(n);
const groups=["すべて","見積中","進行中","請求・答え合わせ・入金待ち","完了・失注"] as const;
type Group=typeof groups[number];
function groupOf(p:ProjectRecord):Group{if(p.status==="失注"||p.status==="入金済み")return"完了・失注";if(["請求済み","答え合わせ済み"].includes(p.status))return"請求・答え合わせ・入金待ち";if(["受注","作業中","納品済み","実績入力済み"].includes(p.status))return"進行中";return"見積中"}
function nextAction(p:ProjectRecord){if(p.status==="見積作成中")return{label:"見積を作る",href:`/projects/${p.id}/estimate`};if(p.status==="見積提出済")return{label:"受注・失注を確認",href:`/projects/${p.id}`};if(p.status==="受注")return{label:"作業を開始",href:`/projects/${p.id}`};if(p.status==="作業中")return{label:"進捗を更新",href:`/projects/${p.id}/progress`};if(p.status==="納品済み")return{label:"実績を入力",href:`/projects/${p.id}/actuals`};if(p.status==="実績入力済み")return{label:"請求書を作成",href:`/projects/${p.id}/billing`};if(p.status==="請求済み")return{label:"答え合わせをする",href:`/projects/${p.id}/review`};if(p.status==="答え合わせ済み")return{label:"入金を確認",href:`/projects/${p.id}/billing`};if(p.status==="入金済み")return{label:"振り返りを見る",href:`/projects/${p.id}/review`};return{label:"案件を見る",href:`/projects/${p.id}`}}
export default function Projects(){const[projects,setProjects]=useState<ProjectRecord[]>([]),[q,setQ]=useState(""),[group,setGroup]=useState<Group>("すべて");useEffect(()=>setProjects(loadProjects()),[]);const counts=useMemo(()=>Object.fromEntries(groups.map(g=>[g,g==="すべて"?projects.length:projects.filter(p=>groupOf(p)===g).length])),[projects]);const list=useMemo(()=>projects.filter(p=>(group==="すべて"||groupOf(p)===group)&&`${p.name}${p.client}${p.category}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>(a.internalDue||a.clientDue||"9999").localeCompare(b.internalDue||b.clientDue||"9999")),[projects,q,group]);return <main className="subpage"><header><div><h1>案件</h1><p>案件の現在地を確認し、次に必要な作業へ直接進めます。</p></div><a href="/projects/new"><button>＋ 新しい案件</button></a></header><section className="summaryCards">{groups.slice(1).map(g=><div key={g}><small>{g}</small><strong>{counts[g]}件</strong></div>)}</section><section className="panel"><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="案件名・顧客名・カテゴリを検索"/></div><nav className="tabs">{groups.map(g=><button key={g} className={group===g?"navActive secondary":"secondary"} onClick={()=>setGroup(g)}>{g} {counts[g]}</button>)}</nav>{list.length===0?<div className="emptyState"><strong>該当する案件はありません</strong><p>条件を変更するか、新しい案件を作成してください。</p></div>:list.map(p=>{const action=nextAction(p),progress=getProjectProgress(p.id),g=groupOf(p);return <div className="projectRow" key={p.id}><a href={`/projects/${p.id}`}><div><strong>{p.name}</strong><small>{p.client} ・ {p.category||"未分類"}</small></div></a><em>{STATUS_LABELS[p.status]}</em><span>{yen(p.amount)}</span><span>納期 {p.clientDue||"未設定"}</span><div className="bar"><i style={{width:`${progress}%`}}/></div><div><small>{g}</small><a href={action.href}><button className="secondary">{action.label} →</button></a></div></div>})}</section></main>}
