export type ProjectStatus="見積作成中"|"見積提出済"|"受注"|"作業中"|"納品済み"|"実績入力済み"|"請求済み"|"答え合わせ済み"|"入金済み"|"失注";
export const PROJECT_FLOW:ProjectStatus[]=["見積作成中","見積提出済","受注","作業中","納品済み","実績入力済み","請求済み","答え合わせ済み","入金済み"];
export const STATUS_LABELS:Record<ProjectStatus,string>={"見積作成中":"見積作成","見積提出済":"見積提出","受注":"受注","作業中":"作業中","納品済み":"納品済み","実績入力済み":"実績入力済み","請求済み":"請求済み","答え合わせ済み":"答え合わせ済み","入金済み":"入金済み","失注":"失注"};
export type ProjectRecord={id:string;name:string;client:string;category:string;status:ProjectStatus;amount:number;clientDue:string;internalDue:string;tags:string[];createdAt:string};
export type CustomerRecord={id:string;name:string;person:string;email:string;createdAt:string};
export type EstimateItem={name:string;qty:number;unit:string;price:number;hours:number;material:number;outsource:number;other:number};
export type EstimateRecord={projectId:string;items:EstimateItem[];updatedAt:string};
export type SpecificationBlock={id:number;type:string;title:string;content:string};
export type SpecificationRecord={projectId:string;blocks:SpecificationBlock[];submitted:boolean;updatedAt:string};
export type EstimateVersion={id:string;projectId:string;version:number;items:EstimateItem[];blocks:SpecificationBlock[];amount:number;status:string;note:string;createdAt:string};
export type WorkRecord={id:number;date:string;task:string;hours:number};
export type CostRecord={id:number;type:string;title:string;amount:number};
export type ExtraRecord={id:number;title:string;amount:number;billable:boolean};
export type ActualRecord={projectId:string;works:WorkRecord[];costs:CostRecord[];extras:ExtraRecord[];updatedAt:string};
export type InvoiceLine={id:number;name:string;qty:number;price:number};
export type BillingRecord={projectId:string;lines:InvoiceLine[];issued:boolean;paid:boolean;dueDate:string;paidDate:string;updatedAt:string};
export type ReviewRecord={projectId:string;score:number;note:string;updatedAt:string};
export type ProgressTask={id:number;title:string;level:number;status:string;progress:number;due:string};
export type ProgressRecord={projectId:string;tasks:ProgressTask[];updatedAt:string};
export type DocumentMeta={projectId:string;estimateNumber:string;invoiceNumber:string;estimateIssueDate:string;estimateValidUntil:string;invoiceIssueDate:string};
const KEYS={projects:"mitsumori-note-projects",customers:"mitsumori-note-customers",estimates:"mitsumori-note-estimates",specifications:"mitsumori-note-specifications",versions:"mitsumori-note-estimate-versions",actuals:"mitsumori-note-actuals",billings:"mitsumori-note-billings",reviews:"mitsumori-note-reviews",progress:"mitsumori-note-progress",documents:"mitsumori-note-document-meta"};
const normalizeStatus=(status:string):ProjectStatus=>status==="完了"?"納品済み":PROJECT_FLOW.includes(status as ProjectStatus)||status==="失注"?status as ProjectStatus:"見積作成中";
const seedProjects:ProjectRecord[]=[{id:"1",name:"コーポレートサイト制作",client:"株式会社ABC",category:"Web制作",status:"作業中",amount:320000,clientDue:"2026-07-31",internalDue:"2026-07-25",tags:["Web","CMS"],createdAt:"2026-07-01"},{id:"2",name:"LPデザイン・実装",client:"山田商店",category:"LP制作",status:"見積提出済",amount:180000,clientDue:"2026-08-02",internalDue:"2026-07-29",tags:["LP"],createdAt:"2026-07-10"}];
export function loadProjects(){if(typeof window==="undefined")return seedProjects;const raw=localStorage.getItem(KEYS.projects);if(!raw){localStorage.setItem(KEYS.projects,JSON.stringify(seedProjects));return seedProjects}try{const parsed=JSON.parse(raw) as Array<Omit<ProjectRecord,"status">&{status:string}>;const normalized=parsed.map(x=>({...x,status:normalizeStatus(x.status)}));if(parsed.some((x,i)=>x.status!==normalized[i].status))localStorage.setItem(KEYS.projects,JSON.stringify(normalized));return normalized}catch{return seedProjects}}
export function saveProjects(data:ProjectRecord[]){if(typeof window!=="undefined")localStorage.setItem(KEYS.projects,JSON.stringify(data))}
export function addProject(data:Omit<ProjectRecord,"id"|"createdAt">){const all=loadProjects();const item:ProjectRecord={...data,id:crypto.randomUUID(),createdAt:new Date().toISOString().slice(0,10)};saveProjects([item,...all]);return item}
export function getProject(id:string){return loadProjects().find(x=>x.id===id)}
export function updateProject(id:string,patch:Partial<ProjectRecord>){const all=loadProjects().map(x=>x.id===id?{...x,...patch}:x);saveProjects(all);return all.find(x=>x.id===id)}
export function getStatusIndex(status:string){return status==="失注"?-1:PROJECT_FLOW.indexOf(normalizeStatus(status))}
export function isAcceptedStatus(status:string){return["受注","作業中","納品済み","実績入力済み","請求済み","答え合わせ済み","入金済み"].includes(normalizeStatus(status))}
export function isActiveStatus(status:string){return!["入金済み","失注"].includes(normalizeStatus(status))}
export function loadEstimates(){if(typeof window==="undefined")return[] as EstimateRecord[];try{return JSON.parse(localStorage.getItem(KEYS.estimates)||"[]") as EstimateRecord[]}catch{return[]}}
export function getEstimate(projectId:string){return loadEstimates().find(x=>x.projectId===projectId)}
export function saveEstimate(projectId:string,items:EstimateItem[]){const all=loadEstimates().filter(x=>x.projectId!==projectId);const record:EstimateRecord={projectId,items,updatedAt:new Date().toISOString()};localStorage.setItem(KEYS.estimates,JSON.stringify([record,...all]));const amount=items.reduce((a,x)=>a+x.qty*x.price,0);updateProject(projectId,{amount});return record}
export function loadSpecifications(){if(typeof window==="undefined")return[] as SpecificationRecord[];try{return JSON.parse(localStorage.getItem(KEYS.specifications)||"[]") as SpecificationRecord[]}catch{return[]}}
export function getSpecification(projectId:string){return loadSpecifications().find(x=>x.projectId===projectId)}
export function saveSpecification(projectId:string,blocks:SpecificationBlock[],submitted=false){const all=loadSpecifications().filter(x=>x.projectId!==projectId);const record:SpecificationRecord={projectId,blocks,submitted,updatedAt:new Date().toISOString()};localStorage.setItem(KEYS.specifications,JSON.stringify([record,...all]));if(submitted)updateProject(projectId,{status:"見積提出済"});return record}
export function loadEstimateVersions(){if(typeof window==="undefined")return[] as EstimateVersion[];try{return JSON.parse(localStorage.getItem(KEYS.versions)||"[]") as EstimateVersion[]}catch{return[]}}
export function getEstimateVersions(projectId:string){return loadEstimateVersions().filter(x=>x.projectId===projectId).sort((a,b)=>b.version-a.version)}
export function createEstimateVersion(projectId:string,note=""){const estimate=getEstimate(projectId),spec=getSpecification(projectId);if(!estimate)return null;const all=loadEstimateVersions(),versions=all.filter(x=>x.projectId===projectId),version=Math.max(0,...versions.map(x=>x.version))+1;const record:EstimateVersion={id:crypto.randomUUID(),projectId,version,items:estimate.items.map(x=>({...x})),blocks:(spec?.blocks||[]).map(x=>({...x})),amount:estimate.items.reduce((a,x)=>a+x.qty*x.price,0),status:"提出済",note,createdAt:new Date().toISOString()};localStorage.setItem(KEYS.versions,JSON.stringify([record,...all]));return record}
export function confirmEstimateVersion(projectId:string,versionId:string){const all=loadEstimateVersions().map(x=>x.projectId===projectId?{...x,status:x.id===versionId?"受注版":x.status==="受注版"?"旧版":x.status}:x);localStorage.setItem(KEYS.versions,JSON.stringify(all));const selected=all.find(x=>x.id===versionId);if(selected){saveEstimate(projectId,selected.items.map(x=>({...x})));saveSpecification(projectId,selected.blocks.map(x=>({...x})),false);updateProject(projectId,{amount:selected.amount,status:"受注"})}return selected}
export function restoreEstimateVersion(versionId:string){const version=loadEstimateVersions().find(x=>x.id===versionId);if(!version)return null;saveEstimate(version.projectId,version.items.map(x=>({...x})));saveSpecification(version.projectId,version.blocks.map(x=>({...x})),false);return version}
export function copyProjectWithEstimate(sourceId:string){const source=getProject(sourceId);if(!source)return null;const item=addProject({name:`${source.name}（コピー）`,client:source.client,category:source.category,status:"見積作成中",amount:source.amount,clientDue:"",internalDue:"",tags:[...source.tags]});const estimate=getEstimate(sourceId);if(estimate)saveEstimate(item.id,estimate.items.map(x=>({...x})));const spec=getSpecification(sourceId);if(spec)saveSpecification(item.id,spec.blocks.map(x=>({...x,id:Date.now()+x.id})),false);return item}
export function loadActuals(){if(typeof window==="undefined")return[] as ActualRecord[];try{return JSON.parse(localStorage.getItem(KEYS.actuals)||"[]") as ActualRecord[]}catch{return[]}}
export function getActual(projectId:string){return loadActuals().find(x=>x.projectId===projectId)}
export function saveActual(projectId:string,works:WorkRecord[],costs:CostRecord[],extras:ExtraRecord[]){const all=loadActuals().filter(x=>x.projectId!==projectId);const record:ActualRecord={projectId,works,costs,extras,updatedAt:new Date().toISOString()};localStorage.setItem(KEYS.actuals,JSON.stringify([record,...all]));const project=getProject(projectId);if(project&&getStatusIndex(project.status)<getStatusIndex("実績入力済み"))updateProject(projectId,{status:"実績入力済み"});return record}
export function loadBillings(){if(typeof window==="undefined")return[] as BillingRecord[];try{return JSON.parse(localStorage.getItem(KEYS.billings)||"[]") as BillingRecord[]}catch{return[]}}
export function getBilling(projectId:string){return loadBillings().find(x=>x.projectId===projectId)}
export function loadReviews(){if(typeof window==="undefined")return[] as ReviewRecord[];try{return JSON.parse(localStorage.getItem(KEYS.reviews)||"[]") as ReviewRecord[]}catch{return[]}}
export function getReview(projectId:string){return loadReviews().find(x=>x.projectId===projectId)}
export function getCompletionState(projectId:string){const billing=getBilling(projectId),review=getReview(projectId);return{invoiceIssued:!!billing?.issued,paymentReceived:!!billing?.paid,reviewCompleted:!!review,complete:!!billing?.paid&&!!review}}
export function saveBilling(projectId:string,data:Omit<BillingRecord,"projectId"|"updatedAt">){const all=loadBillings().filter(x=>x.projectId!==projectId);const record:BillingRecord={projectId,...data,updatedAt:new Date().toISOString()};localStorage.setItem(KEYS.billings,JSON.stringify([record,...all]));const review=getReview(projectId);if(data.paid&&review)updateProject(projectId,{status:"入金済み"});else if(review)updateProject(projectId,{status:"答え合わせ済み"});else if(data.issued)updateProject(projectId,{status:"請求済み"});else{const project=getProject(projectId);if(project&&["請求済み","答え合わせ済み","入金済み"].includes(project.status))updateProject(projectId,{status:"実績入力済み"})}return record}
export function saveReview(projectId:string,score:number,note:string){const all=loadReviews().filter(x=>x.projectId!==projectId);const record:ReviewRecord={projectId,score,note,updatedAt:new Date().toISOString()};localStorage.setItem(KEYS.reviews,JSON.stringify([record,...all]));const billing=getBilling(projectId);updateProject(projectId,{status:billing?.paid?"入金済み":"答え合わせ済み"});return record}
export function loadProgress(){if(typeof window==="undefined")return[] as ProgressRecord[];try{return JSON.parse(localStorage.getItem(KEYS.progress)||"[]") as ProgressRecord[]}catch{return[]}}
export function getProgress(projectId:string){return loadProgress().find(x=>x.projectId===projectId)}
export function saveProgress(projectId:string,tasks:ProgressTask[]){const all=loadProgress().filter(x=>x.projectId!==projectId);const record:ProgressRecord={projectId,tasks,updatedAt:new Date().toISOString()};localStorage.setItem(KEYS.progress,JSON.stringify([record,...all]));const roots=tasks.filter(x=>x.level===0),total=roots.length?Math.round(roots.reduce((a,x)=>a+x.progress,0)/roots.length):0;const project=getProject(projectId);if(project&&getStatusIndex(project.status)<=getStatusIndex("納品済み")){if(total===100)updateProject(projectId,{status:"納品済み"});else if(total>0)updateProject(projectId,{status:"作業中"})}return record}
export function getProjectProgress(projectId:string){const tasks=getProgress(projectId)?.tasks||[];const roots=tasks.filter(x=>x.level===0);return roots.length?Math.round(roots.reduce((a,x)=>a+x.progress,0)/roots.length):0}
export function getSimilarProjectSuggestions(category:string,tags:string[]){return loadProjects().map(p=>{const actual=getActual(p.id),billing=getBilling(p.id),review=getReview(p.id);const eligible=!!review&&["答え合わせ済み","入金済み"].includes(p.status);const tagMatches=p.tags.filter(t=>tags.some(x=>x.toLowerCase()===t.toLowerCase())).length;const similarity=(p.category===category?60:0)+Math.min(30,tagMatches*15)+10;const hours=actual?.works.reduce((a,x)=>a+x.hours,0)||getEstimate(p.id)?.items.reduce((a,x)=>a+x.hours,0)||0;const amount=billing?.lines.reduce((a,x)=>a+x.qty*x.price,0)||p.amount;return{project:p,similarity,hours,amount,score:review?.score||0,eligible}}).filter(x=>x.eligible&&x.similarity>0).sort((a,b)=>b.similarity-a.similarity).slice(0,3)}
export function loadCustomers(){if(typeof window==="undefined")return[] as CustomerRecord[];try{return JSON.parse(localStorage.getItem(KEYS.customers)||"[]") as CustomerRecord[]}catch{return[]}}
export function addCustomer(data:Omit<CustomerRecord,"id"|"createdAt">){const item={...data,id:crypto.randomUUID(),createdAt:new Date().toISOString().slice(0,10)};const all=loadCustomers();localStorage.setItem(KEYS.customers,JSON.stringify([item,...all]));return item}
export function loadDocumentMeta(){if(typeof window==="undefined")return[] as DocumentMeta[];try{return JSON.parse(localStorage.getItem(KEYS.documents)||"[]") as DocumentMeta[]}catch{return[]}}
const ymd=()=>new Date().toISOString().slice(0,10);
const plusDays=(date:string,days:number)=>{const d=new Date(date+"T00:00:00");d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
export function getDocumentMeta(projectId:string){const existing=loadDocumentMeta().find(x=>x.projectId===projectId);if(existing)return existing;const today=ymd(),seq=String(loadDocumentMeta().length+1).padStart(4,"0"),year=today.slice(0,4);const record:DocumentMeta={projectId,estimateNumber:`EST-${year}-${seq}`,invoiceNumber:`INV-${year}-${seq}`,estimateIssueDate:today,estimateValidUntil:plusDays(today,30),invoiceIssueDate:today};saveDocumentMeta(record);return record}
export function saveDocumentMeta(record:DocumentMeta){const all=loadDocumentMeta().filter(x=>x.projectId!==record.projectId);localStorage.setItem(KEYS.documents,JSON.stringify([record,...all]));return record}