export type ProjectRecord={id:string;name:string;client:string;category:string;status:string;amount:number;clientDue:string;internalDue:string;tags:string[];createdAt:string};
export type CustomerRecord={id:string;name:string;person:string;email:string;createdAt:string};
export type EstimateItem={name:string;qty:number;unit:string;price:number;hours:number;material:number;outsource:number;other:number};
export type EstimateRecord={projectId:string;items:EstimateItem[];updatedAt:string};
export type WorkRecord={id:number;date:string;task:string;hours:number};
export type CostRecord={id:number;type:string;title:string;amount:number};
export type ExtraRecord={id:number;title:string;amount:number;billable:boolean};
export type ActualRecord={projectId:string;works:WorkRecord[];costs:CostRecord[];extras:ExtraRecord[];updatedAt:string};
export type InvoiceLine={id:number;name:string;qty:number;price:number};
export type BillingRecord={projectId:string;lines:InvoiceLine[];issued:boolean;paid:boolean;dueDate:string;paidDate:string;updatedAt:string};
export type ReviewRecord={projectId:string;score:number;note:string;updatedAt:string};
export type ProgressTask={id:number;title:string;level:number;status:string;progress:number;due:string};
export type ProgressRecord={projectId:string;tasks:ProgressTask[];updatedAt:string};
const KEYS={projects:"mitsumori-note-projects",customers:"mitsumori-note-customers",estimates:"mitsumori-note-estimates",actuals:"mitsumori-note-actuals",billings:"mitsumori-note-billings",reviews:"mitsumori-note-reviews",progress:"mitsumori-note-progress"};
const seedProjects:ProjectRecord[]=[{id:"1",name:"コーポレートサイト制作",client:"株式会社ABC",category:"Web制作",status:"作業中",amount:320000,clientDue:"2026-07-31",internalDue:"2026-07-25",tags:["Web","CMS"],createdAt:"2026-07-01"},{id:"2",name:"LPデザイン・実装",client:"山田商店",category:"LP制作",status:"見積提出済",amount:180000,clientDue:"2026-08-02",internalDue:"2026-07-29",tags:["LP"],createdAt:"2026-07-10"}];
export function loadProjects(){if(typeof window==="undefined")return seedProjects;const raw=localStorage.getItem(KEYS.projects);if(!raw){localStorage.setItem(KEYS.projects,JSON.stringify(seedProjects));return seedProjects}try{return JSON.parse(raw) as ProjectRecord[]}catch{return seedProjects}}
export function saveProjects(data:ProjectRecord[]){if(typeof window!=="undefined")localStorage.setItem(KEYS.projects,JSON.stringify(data))}
export function addProject(data:Omit<ProjectRecord,"id"|"createdAt">){const all=loadProjects();const item:ProjectRecord={...data,id:crypto.randomUUID(),createdAt:new Date().toISOString().slice(0,10)};saveProjects([item,...all]);return item}
export function getProject(id:string){return loadProjects().find(x=>x.id===id)}
export function updateProject(id:string,patch:Partial<ProjectRecord>){const all=loadProjects().map(x=>x.id===id?{...x,...patch}:x);saveProjects(all);return all.find(x=>x.id===id)}
export function loadEstimates(){if(typeof window==="undefined")return[] as EstimateRecord[];try{return JSON.parse(localStorage.getItem(KEYS.estimates)||"[]") as EstimateRecord[]}catch{return[]}}
export function getEstimate(projectId:string){return loadEstimates().find(x=>x.projectId===projectId)}
export function saveEstimate(projectId:string,items:EstimateItem[]){const all=loadEstimates().filter(x=>x.projectId!==projectId);const record:EstimateRecord={projectId,items,updatedAt:new Date().toISOString()};localStorage.setItem(KEYS.estimates,JSON.stringify([record,...all]));const amount=items.reduce((a,x)=>a+x.qty*x.price,0);updateProject(projectId,{amount});return record}
export function copyProjectWithEstimate(sourceId:string){const source=getProject(sourceId);if(!source)return null;const item=addProject({name:`${source.name}（コピー）`,client:source.client,category:source.category,status:"見積作成中",amount:source.amount,clientDue:"",internalDue:"",tags:[...source.tags]});const estimate=getEstimate(sourceId);if(estimate)saveEstimate(item.id,estimate.items.map(x=>({...x})));return item}
export function loadActuals(){if(typeof window==="undefined")return[] as ActualRecord[];try{return JSON.parse(localStorage.getItem(KEYS.actuals)||"[]") as ActualRecord[]}catch{return[]}}
export function getActual(projectId:string){return loadActuals().find(x=>x.projectId===projectId)}
export function saveActual(projectId:string,works:WorkRecord[],costs:CostRecord[],extras:ExtraRecord[]){const all=loadActuals().filter(x=>x.projectId!==projectId);const record:ActualRecord={projectId,works,costs,extras,updatedAt:new Date().toISOString()};localStorage.setItem(KEYS.actuals,JSON.stringify([record,...all]));return record}
export function loadBillings(){if(typeof window==="undefined")return[] as BillingRecord[];try{return JSON.parse(localStorage.getItem(KEYS.billings)||"[]") as BillingRecord[]}catch{return[]}}
export function getBilling(projectId:string){return loadBillings().find(x=>x.projectId===projectId)}
export function saveBilling(projectId:string,data:Omit<BillingRecord,"projectId"|"updatedAt">){const all=loadBillings().filter(x=>x.projectId!==projectId);const record:BillingRecord={projectId,...data,updatedAt:new Date().toISOString()};localStorage.setItem(KEYS.billings,JSON.stringify([record,...all]));if(data.paid)updateProject(projectId,{status:"入金済み"});else if(data.issued)updateProject(projectId,{status:"請求済み"});return record}
export function loadReviews(){if(typeof window==="undefined")return[] as ReviewRecord[];try{return JSON.parse(localStorage.getItem(KEYS.reviews)||"[]") as ReviewRecord[]}catch{return[]}}
export function getReview(projectId:string){return loadReviews().find(x=>x.projectId===projectId)}
export function saveReview(projectId:string,score:number,note:string){const all=loadReviews().filter(x=>x.projectId!==projectId);const record:ReviewRecord={projectId,score,note,updatedAt:new Date().toISOString()};localStorage.setItem(KEYS.reviews,JSON.stringify([record,...all]));return record}
export function loadProgress(){if(typeof window==="undefined")return[] as ProgressRecord[];try{return JSON.parse(localStorage.getItem(KEYS.progress)||"[]") as ProgressRecord[]}catch{return[]}}
export function getProgress(projectId:string){return loadProgress().find(x=>x.projectId===projectId)}
export function saveProgress(projectId:string,tasks:ProgressTask[]){const all=loadProgress().filter(x=>x.projectId!==projectId);const record:ProgressRecord={projectId,tasks,updatedAt:new Date().toISOString()};localStorage.setItem(KEYS.progress,JSON.stringify([record,...all]));const roots=tasks.filter(x=>x.level===0),total=roots.length?Math.round(roots.reduce((a,x)=>a+x.progress,0)/roots.length):0;if(total===100)updateProject(projectId,{status:"完了"});else if(total>0)updateProject(projectId,{status:"作業中"});return record}
export function getProjectProgress(projectId:string){const tasks=getProgress(projectId)?.tasks||[];const roots=tasks.filter(x=>x.level===0);return roots.length?Math.round(roots.reduce((a,x)=>a+x.progress,0)/roots.length):0}
export function getSimilarProjectSuggestions(category:string,tags:string[]){return loadProjects().map(p=>{const actual=getActual(p.id),billing=getBilling(p.id),review=getReview(p.id);const tagMatches=p.tags.filter(t=>tags.some(x=>x.toLowerCase()===t.toLowerCase())).length;const similarity=(p.category===category?60:0)+Math.min(30,tagMatches*15)+(review?10:0);const hours=actual?.works.reduce((a,x)=>a+x.hours,0)||getEstimate(p.id)?.items.reduce((a,x)=>a+x.hours,0)||0;const amount=billing?.lines.reduce((a,x)=>a+x.qty*x.price,0)||p.amount;return{project:p,similarity,hours,amount,score:review?.score||0}}).filter(x=>x.similarity>0).sort((a,b)=>b.similarity-a.similarity).slice(0,3)}
export function loadCustomers(){if(typeof window==="undefined")return[] as CustomerRecord[];try{return JSON.parse(localStorage.getItem(KEYS.customers)||"[]") as CustomerRecord[]}catch{return[]}}
export function addCustomer(data:Omit<CustomerRecord,"id"|"createdAt">){const item={...data,id:crypto.randomUUID(),createdAt:new Date().toISOString().slice(0,10)};const all=loadCustomers();localStorage.setItem(KEYS.customers,JSON.stringify([item,...all]));return item}
